provider_type = {
    1: 'Hospital',
    2: 'Skilled Nursing Facility/Nursing Facility (DuallyCertified)',
    3: 'Skilled Nursing Facility/Nursing Facility (DistinctPart)',
    4: 'Skilled Nursing Facility',
    5: 'Home Health Agency',
    6: 'Psychiatric Residential Treatment Facility',
    7: 'Portable X-Ray Supplier',
    8: 'Outpatient Physical Therapy Speech Pathology',
    9: 'End Stage Renal Disease Facility',
    10: 'Nursing Facility',
    11: 'Intermediate Care Facility/Individuals with Intellectual Disabilities',
    12: 'Rural Health Clinic',
    14: 'Comprehensive Outpatient Rehab Facility',
    15: 'Ambulatory Surgical Center',
    16: 'Hospice',
    17: 'Organ Procurement Organization',
    19: 'Community Mental Health Center',
    21: 'Federally Qualified Health Center',
}
