provider_type = {
    1: 'Hospital',
    2: 'Skilled Nursing Facility/Nursing Facility (DuallyCertified)',
    3: 'Skilled Nursing Facility/Nursing Facility (DistinctPart)',
    4: 'Skilled Nursing Facility',
    5: 'Home Health Agency',
    6: 'Psychiatric Residential Treatment Facility',
    7: 'Portable X-Ray Supplier',
    8: 'Outpatient Physical Therapy Speech Pathology',
    9: 'End Stage Renal Disease Facility',
    10: 'Nursing Facility',
    11: 'Intermediate Care Facility/Individuals with Intellectual Disabilities',
    12: 'Rural Health Clinic',
    14: 'Comprehensive Outpatient Rehab Facility',
    15: 'Ambulatory Surgical Center',
    16: 'Hospice',
    17: 'Organ Procurement Organization',
    19: 'Community Mental Health Center',
    21: 'Federally Qualified Health Center',
}

sub_category = {
    1: "Short Term",
    2: "Long Term",
    3: "Religious Non-Medical Health Care Institutions",
    4: "Psychiatric",
    5: "Rehabilitation",
    6: "Childrens Hospitals",
    7: "Distinct Part Psychiatric Hospital",
    11: "Critical Access Hospitals",
    20: "Transplant Hospitals",
    22: "Medicaid Only Short-Term Hospitals",
    23: "Medicaid Only Childrens Hospitals",
    24: "Medicaid Only Children's Psychiatric",
    25: "Medicaid Only Psychiatric Hospitals",
    26: "Medicaid Only Rehabilitation Hospitals",
    27: "Medicaid Only Long-Term Hospitals",
    28: "Rural Emergency Hospital"
}

program_termination_status = {
    0: "ACTIVE PROVIDER",
    1: "VOLUNTARY-MERGER, CLOSURE",
    2: "VOLUNTARY-DISSATISFACTION WITH REIMBURSEMENT",
    3: "VOLUNTARY-RISK OF INVOLUNTARY TERMINATION",
    4: "VOLUNTARY-OTHER REASON FOR WITHDRAWAL",
    5: "INVOLUNTARY-FAILURE TO MEET HEALTH/SAFETY REQ",
    6: "INVOLUNTARY-FAILURE TO MEET AGREEMENT",
    7: "OTHER-PROVIDER STATUS CHANGE",
    8: "NONPAYMENT OF FEES - CLIA Only",
    9: "REV/UNSUCCESSFUL PARTICIPATION IN PT - CLIA Only",
    10: "REV/OTHER REASON - CLIA Only",
    11: "INCOMPLETE CLIA APPLICATION INFORMATION - CLIA Only",
    12: "NO LONGER PERFORMING TESTS - CLIA Only",
    13: "MULTIPLE TO SINGLE SITE CERTIFICATE - CLIA Only",
    14: "SHARED LABORATORY - CLIA Only",
    15: "FAILURE TO RENEW WAIVER PPM CERTIFICATE - CLIA Only",
    16: "DUPLICATE CLIA NUMBER - CLIA Only"
}